### ISSUE TITLE
Wechat button can't work

### ISSUE THREAD

**Issue by xinfengwu** [theme-next/theme-next-needmoreshare2#10]
clicked Wechat button,it can't work at all."loading wechat image"stays all the time.mywebsite URL:[IT达摩院](www.itdamo.org)

**Comment by LEAFERx** [comment]
Solved #9.
Sorry for my absent.

**Comment by qcmoke** [comment]
希望早些能修复微信分享点击无效这个bug，我将依依东望~

**Comment by LEAFERx** [comment]
@qcmoke 已经修复了 请更新库至最新试试
