### ISSUE TITLE
Issue about when using a minifier like clean-css

### ISSUE THREAD

**Issue by tsanie** [theme-next/theme-next-needmoreshare2#3]
Some people meet an issue when they use the minifier to process these css files, like https://github.com/theme-next/hexo-filter-optimize/issues/3 and ~~https://github.com/theme-next/hexo-filter-optimize/issues/4#issuecomment-361937181~~ (_it's just the similar problem but not using the minifier_)

It is caused by the `@import` statement in the `needsharebutton.css`, but I'm not quite sure whether it is an issue of clean-css or not.

And I find it is not a good way by using `@import` in a css, the imported file need to wait until the first css download completely, then it starts to download, like

![image](https://user-images.githubusercontent.com/980449/35656694-ac1981d0-0733-11e8-97b0-8106d8908708.png)

I think there are 2 ways to avoid this problem, and maybe could improves the performance (but just a little I think)

- put another `<link>` for `font-embedded.css` above the `needsharebutton.css`, and remove the `@import` in the `needsharebutton.css`, then the browser could start to download the two files in the same time
  ![image](https://user-images.githubusercontent.com/980449/35656934-cd01a76e-0734-11e8-8ff5-e9fd75ebe474.png)

- just use the minified version provided by https://github.com/revir/need-more-share2/blob/master/dist/needsharebutton.min.css , the two css files were inlined into the one.

**Comment by LEAFERx** [comment]
i dont really have time for this now.
maybe you could help by making a pr?
if not, i will fix this, but cant promise when...

**Comment by LEAFERx** [comment]
#5 merged. Close issue.
