### ISSUE TITLE
Wechat QR has something wrong , and want a QQ feature .

### ISSUE THREAD

**Issue by xiekeyi98** [theme-next/theme-next-needmoreshare2#8]
1. Like this , I can not load the QR successfully .
![image](https://user-images.githubusercontent.com/7782671/39357908-d67d2ed0-4a46-11e8-9c68-cc3677ffbe56.png)

2. Want implement the QQ(OICQ) .

**Comment by LEAFERx** [comment]
For 1, wechat sharing works fine in my website(leaferx.online). Need more detailed info to find what's wrong.
For 2, since Qzone sharing is available, QQ sharing is not necessary from my point of view. Either copy the link or share it to Qzone then QQ can do this. However, pull request is always welcomed.

**Comment by xiekeyi98** [comment]
1.  My blog can not work well as your blog ( xiekeyi98.com) , what more infomation I should give ?
2.  Alright .

**Comment by LEAFERx** [comment]
try update your plugin to the newest version (master)
may caused by #4

**Comment by xiekeyi98** [comment]
Sorry , I use the NexT v6.2.0. At the first , I think this version have included the plugin is the newest version.

By the way ,  I found the theme/source/lib have not the neemoreshare plugin , and it included in the theme . Has anyway to update?

**Comment by ivan-nginx** [comment]
@xiekeyi98 all NexT version 6.x not included 3rd-party libraries like this, they must be installed separately. How to install this plugin written in [main readme of this plugin](https://github.com/theme-next/theme-next-needmoreshare2).

For more information read [Plugins section](https://github.com/theme-next/hexo-theme-next#plugins) in main NexT readme.

**Comment by xiekeyi98** [comment]
Thank you very much .
